layout_spectrum: 0.8978124
typography_spectrum: 0.2253671
color:
  saturation: 0.4089258
  lightness: 0.3459439
  brandStrength: 0.9599978
  rhythmicContrast: 0.4580248
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: MID
